ALTER TABLE student ALTER COLUMN grade SET DATA TYPE VARCHAR(1);
ALTER TABLE student ALTER COLUMN grade SET NOT NULL;

ALTER TABLE student ALTER COLUMN classroom SET DATA TYPE VARCHAR(1);
ALTER TABLE student ALTER COLUMN classroom SET NOT NULL;

ALTER TABLE book ALTER COLUMN title SET DATA TYPE VARCHAR(120);
ALTER TABLE book ALTER COLUMN title SET NOT NULL;

ALTER TABLE book ALTER COLUMN author SET DATA TYPE VARCHAR(80);
ALTER TABLE book ALTER COLUMN author SET NOT NULL;
